//need to remake this so that it generates new lists
export const sparseInitialNodes = [
  {
    id: "1",
    type: "nodeVis",
    data: { value: 1, startNode: true, visited: false, visiting: false },
    position: { x: 866.0, y: 0.0 },
    className: "circle",
  },
  {
    id: "2",
    type: "nodeVis",
    data: { value: 2, startNode: false, visited: false, visiting: false },
    position: { x: 858.0, y: 722.0 },
    className: "circle",
  },
  {
    id: "3",
    type: "nodeVis",
    data: { value: 3, startNode: false, visited: false, visiting: false },
    position: { x: 1188.0, y: 304.0 },
    className: "circle",
  },
  {
    id: "4",
    type: "nodeVis",
    data: { value: 4, startNode: false, visited: false, visiting: false },
    position: { x: 590.0, y: -49.0 },
    className: "circle",
  },
  {
    id: "5",
    type: "nodeVis",
    data: { value: 5, startNode: false, visited: false, visiting: false },
    position: { x: 586.0, y: 524.0 },
    className: "circle",
  },
  {
    id: "6",
    type: "nodeVis",
    data: { value: 6, startNode: false, visited: false, visiting: false },
    position: { x: 824.0, y: 324.0 },
    className: "circle",
  },
  {
    id: "7",
    type: "nodeVis",
    data: { value: 7, startNode: false, visited: false, visiting: false },
    position: { x: 990.0, y: 250.0 },
    className: "circle",
  },
  {
    id: "8",
    type: "nodeVis",
    data: { value: 8, startNode: false, visited: false, visiting: false },
    position: { x: 450.0, y: 52.0 },
    className: "circle",
  },
  {
    id: "9",
    type: "nodeVis",
    data: { value: 9, startNode: false, visited: false, visiting: false },
    position: { x: 192.0, y: 430.0 },
    className: "circle",
  },
  {
    id: "10",
    type: "nodeVis",
    data: { value: 10, startNode: false, visited: false, visiting: false },
    position: { x: 318.0, y: 172.0 },
    className: "circle",
  },
  {
    id: "11",
    type: "nodeVis",
    data: { value: 11, startNode: false, visited: false, visiting: false },
    position: { x: 418.0, y: 398.0 },
    className: "circle",
  },
  {
    id: "12",
    type: "nodeVis",
    data: { value: 12, startNode: false, visited: false, visiting: false },
    position: { x: 482.0, y: 722.0 },
    className: "circle",
  },
  {
    id: "13",
    type: "nodeVis",
    data: { value: 13, startNode: false, visited: false, visiting: false },
    position: { x: 716.0, y: 188.0 },
    className: "circle",
  },
  {
    id: "14",
    type: "nodeVis",
    data: { value: 14, startNode: false, visited: false, visiting: false },
    position: { x: 738.0, y: 494.0 },
    className: "circle",
  },
  {
    id: "15",
    type: "nodeVis",
    data: { value: 15, startNode: false, visited: false, visiting: false },
    position: { x: 968.0, y: 500.0 },
    className: "circle",
  },
  {
    id: "16",
    type: "nodeVis",
    data: { value: 16, startNode: false, visited: false, visiting: false },
    position: { x: 242.0, y: -99.2 },
    className: "circle",
  },
  {
    id: "17",
    type: "nodeVis",
    data: { value: 17, startNode: false, visited: false, visiting: false },
    position: { x: 90.0, y: 570.0 },
    className: "circle",
  },
  {
    id: "18",
    type: "nodeVis",
    data: { value: 18, startNode: false, visited: false, visiting: false },
    position: { x: 2.0, y: 274.0 },
    className: "circle",
  },
  {
    id: "19",
    type: "nodeVis",
    data: { value: 19, startNode: false, visited: false, visiting: false },
    position: { x: 290.0, y: 600.0 },
    className: "circle",
  },
  {
    id: "20",
    type: "nodeVis",
    data: { value: 20, startNode: false, visited: false, visiting: false },
    position: { x: 144.0, y: 72.0 },
    className: "circle",
  },
];

export const sparseInitialEdges = [
  { id: "e1-4", source: "1", target: "4" },
  { id: "e1-9", source: "1", target: "9" },
  { id: "e1-10", source: "1", target: "10" },
  { id: "e2-5", source: "2", target: "5" },
  { id: "e2-6", source: "2", target: "6" },
  { id: "e3-7", source: "3", target: "7" },
  { id: "e4-8", source: "4", target: "8" },
  { id: "e5-11", source: "5", target: "11" },
  { id: "e5-12", source: "5", target: "12" },
  { id: "e6-13", source: "6", target: "13" },
  { id: "e6-14", source: "6", target: "14" },
  { id: "e7-15", source: "7", target: "15" },
  { id: "e8-16", source: "8", target: "16" },
  { id: "e9-17", source: "9", target: "17" },
  { id: "e9-18", source: "9", target: "18" },
  { id: "e10-19", source: "10", target: "19" },
  { id: "e10-20", source: "10", target: "20" },
];
